# Generated by Django 4.0.4 on 2022-05-18 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=2000)),
            ],
            options={
                'verbose_name': 'Mijozlar bilan aloqa',
                'verbose_name_plural': 'Mijozlar bilan aloqa',
            },
        ),
    ]
