# Generated by Django 4.0.4 on 2022-05-23 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='ip',
            field=models.CharField(default='127.0.0.1', max_length=300),
            preserve_default=False,
        ),
    ]
