# Generated by Django 4.0.4 on 2022-05-23 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contact_create_date_contact_create_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Общение с клиентами', 'verbose_name_plural': 'Общение с клиентами'},
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_date',
            field=models.DateField(auto_now=True, verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='create_time',
            field=models.TimeField(auto_now=True, verbose_name='Время'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='first_name',
            field=models.CharField(max_length=300, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='ip',
            field=models.CharField(max_length=300, verbose_name='IP адрес'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='last_name',
            field=models.CharField(max_length=300, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=2000, verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=300, verbose_name='Телефон'),
        ),
    ]
