# Generated by Django 4.1.1 on 2022-09-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('image', models.ImageField(upload_to='site_logo/')),
            ],
            options={
                'verbose_name': 'Логотип сайта',
                'verbose_name_plural': 'Логотип сайта',
            },
        ),
    ]
